version: '3'
services:
  test-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - ${TEST_MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${TEST_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${TEST_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${TEST_MYSQL_USER}
      MYSQL_PASSWORD: ${TEST_MYSQL_PASSWORD}
    networks:
      - textgarret

networks:
  textgarret: